=== bkumars22/SupplyChainPlatformProject/src/main/resources/config/search/SearchDefSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:jxb="http://java.sun.com/xml/ns/jaxb" jxb:version="2.0">
	<xs:annotation>
		<xs:documentation>Defines the schema for modeling a search page in
			the
			core PCM infrastructure.
		</xs:documentation>
	</xs:annotation>
	<xs:element name="SearchFormDefinition" type="SearchFormDefinitionType" />
	<xs:complexType name="SearchParametersType">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="Text" type="TextType" />
			<xs:element name="List" type="ListType" />
			<xs:element name="Date" type="DateType" />
			<xs:element name="MultiText" type="MultiTextType" />
		</xs:choice>
		<xs:attribute name="groupName" type="xs:string" default="DEFAULT" use="optional"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="SearchParameterType" abstract="true">
		<xs:sequence>
			<xs:element name="Expression" type="xs:string" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="Property" type="PropertyType"
				minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="DefaultExpressions" type="DefaultExpressionsType"
						minOccurs="0" maxOccurs="1" ></xs:element>
		</xs:sequence>
		<xs:attribute type="xs:string" name="name" use="optional" />
		<xs:attribute type="xs:string" name="labelKey" use="optional" />
		<xs:attribute type="xs:string" name="dataType" use="optional" />
		<xs:attribute type="xs:boolean" name="required" use="optional" />
		<xs:attribute name="includeIfPropTrue" type="xs:string" use="optional"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="ListType">
		<xs:complexContent>
			<xs:extension base="SearchParameterType">
				<xs:sequence>
					<xs:element name="ListValue" type="ListValueType"
						minOccurs="0" maxOccurs="unbounded">
					</xs:element>
				</xs:sequence>
				<xs:attribute type="xs:boolean" name="multiSelect"
					use="required" />
				<xs:attribute type="xs:string" name="initializer"
					use="optional" />
				<xs:attribute type="xs:string" name="initializerData"
					use="optional" />
				<xs:attribute name="dataFormat" type="xs:string"></xs:attribute>
				<xs:attribute name="checkIfTrue" type="xs:string"></xs:attribute>
				<xs:attribute type="xs:boolean" name="multiValue"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ListValueType">
		<xs:attribute type="xs:string" name="label" use="required" />
		<xs:attribute type="xs:string" name="value" use="required" />
	</xs:complexType>

	<xs:complexType name="OrderByType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="fieldName" use="optional">
					<xs:annotation>
						<xs:documentation>This is the name of the HQL column that will be
							used in the order
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute type="xs:string" name="colummName" use="optional">
					<xs:annotation>
						<xs:documentation>This is the name you have defined for the
							column. It is used by the UI to connect an order by widget to
							this clause
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute type="xs:string" name="default" use="optional">
					<xs:annotation>
						<xs:documentation>If default is set, it means this orderby is on
							and cannot be turned off by the user. They may change the
							direction.
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="GroupByType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="fieldName" use="optional">
					<xs:annotation>
						<xs:documentation>This is the name of the HQL column that will be
							used for Group By
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute type="xs:string" name="colummName" use="optional">
					<xs:annotation>
						<xs:documentation>This is the name you have defined for the
							column. It is used by the UI to connect a Group by widget to
							this clause
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="FilterExpressionType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="name" />
				<xs:attribute name="type" type="xs:string" use="optional"></xs:attribute>
				<xs:attribute name="dataType" type="xs:string" use="optional"></xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="TextType">
		<xs:complexContent>
			<xs:extension base="AbstractTextType">
				<xs:attribute type="xs:string" name="finderName"
					use="optional" />
				<xs:attribute name="matchType" use="optional"
					type="MatchType" />
				<xs:attribute name="checkIfTrue" type="xs:string"></xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="MultiTextType">
		<xs:complexContent>
			<xs:extension base="AbstractTextType">
				<xs:attribute type="MatchType" name="matchType" use="optional" />
				<xs:attribute type="xs:string" name="finderName" use="optional" />
				<xs:attribute type="xs:string" name="delimiter" use="optional"
					default=";" />
				<xs:attribute type="xs:int" name="rows" use="optional"
					default="3" />
				<xs:attribute name="popupFinderName" type="xs:string"></xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="SourceType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="keys" />
				<xs:attribute name="queryType" type="querySimpleType"  use="optional"/>
				<xs:attribute name="transformDefinition" type="xs:string"
					use="optional">
					<xs:annotation>
						<xs:documentation>Optional path to the transformation definition.
							The transformation can be applied to the result of the source
							query
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="FiltersType">
		<xs:sequence>
			<xs:element type="FilterExpressionType" name="FilterExpression"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SearchFormDefinitionType">
		<xs:sequence>
			<xs:element type="SourceType" name="Source" minOccurs="1"
				maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Models the select portion of a HQL statement
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="ExtractSourceType" name="ExtractSource"
				minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Extract source is used to generate an XSL file
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="FiltersType" name="Filters" minOccurs="0"
				maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Filter expressions are
						and not used by the
						critera displayed to users
						They are used to construct fixed
						criteria based on if the named
						parameter
						is present in the list of
						parameter values passed to the query
						execution
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="GroupByType" name="GroupBy" maxOccurs="unbounded"
				minOccurs="0" />
			<xs:element type="OrderByType" name="OrderBy" maxOccurs="unbounded"
				minOccurs="0" />
			<xs:element type="SearchParametersType" name="SearchParameters"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute type="xs:string" name="name" use="required" />
	</xs:complexType>

	<xs:complexType name="PropertyType">
		<xs:attribute name="name" type="xs:string"></xs:attribute>
		<xs:attribute name="value" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="DefaultExpressionsType">
		<xs:sequence>
			<xs:element type="ExprType"
				name="Expr" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ExprType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="name" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="ExtractSourceType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="extractWriterClass" type="xs:string"
					use="optional" />
				<xs:attribute name="extractWriterProps" type="xs:string"
					use="optional" />
				<xs:attribute name="transformDefinition" type="xs:string"
					use="optional">
					<xs:annotation>
						<xs:documentation>
							Optional path to the transformation
							definition.
							The transformation will be
							loaded and passed to the extract class.
							Standard extracts use this to transformt the
							result set from the
							extractSource.
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute name="extractTemplateConfig" type="xs:string">
				</xs:attribute>
				<xs:attribute name="extractTemplate" type="xs:string"></xs:attribute>
				<xs:attribute name="queryType" type="querySimpleType"  use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="AbstractTextType" abstract="true">
		<xs:complexContent>
			<xs:restriction base="SearchParameterType">
				<xs:sequence>
					<xs:element name="Expression" type="xs:string"
						maxOccurs="1" minOccurs="1" />
					<xs:element name="Property" type="PropertyType"
						minOccurs="0" maxOccurs="unbounded"></xs:element>
					<xs:element name="DefaultExpressions" type="DefaultExpressionsType"
						minOccurs="0" maxOccurs="1" ></xs:element>
				</xs:sequence>
				<xs:attribute name="dataType" type="xs:string" fixed="TEXT" />
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="DateType">
		<xs:complexContent>
			<xs:extension base="AbstractDateType">
				<xs:attribute name="matchType" type="MatchType"></xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>


	<xs:complexType name="AbstractDateType" abstract="true">
		<xs:complexContent>
			<xs:restriction base="SearchParameterType">
				<xs:sequence>
					<xs:element name="Expression" type="xs:string"
						maxOccurs="1" minOccurs="1" />
					<xs:element name="Property" type="PropertyType"
						minOccurs="0" maxOccurs="unbounded">
					</xs:element>
				</xs:sequence>
				<xs:attribute name="dataType" type="xs:string" fixed="DATE"/>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>

	<xs:simpleType name="MatchType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="EXACT"></xs:enumeration>
			<xs:enumeration value="IEXACT"></xs:enumeration>
			<xs:enumeration value="LIKE"></xs:enumeration>
			<xs:enumeration value="ILIKE"></xs:enumeration>
			<xs:enumeration value="GE"></xs:enumeration>
			<xs:enumeration value="GT"></xs:enumeration>
			<xs:enumeration value="LE"></xs:enumeration>
			<xs:enumeration value="LT"></xs:enumeration>
			<xs:enumeration value="IN"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="querySimpleType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="SQL"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== bkumars22/SupplyChainPlatformProject/src/main/resources/config/search/SearchDefCostForecastVariance.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- PLEASE READ =========== This search def is for cost forecast variance 
	search tied to the Workflow Cost Forecast Variance Report -->

<SearchFormDefinition
	name="SearchDefCostForecastVarianceReport"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="SearchDefSchema.xsd">
	<Source>
		select fg, pfg
		from FunctionalGroup fg
		left join fg.parentFunctionalGroup pfg
		full join fg.functionalGroupItems im
	</Source>

	<!-- Filter expressions are fixed and not used by the criteria displayed 
		to users They are used to construct fixed criteria based on if the named 
		parameter is present in the list of parameter values passed to the query 
		execution -->
	<Filters>
		<FilterExpression name="cfgTypeFilter" type="FIXED">fg.type = 'CFG'</FilterExpression>
		<FilterExpression name="itemTypeFilter" type="FIXED">(upper(im.itemType) not in ('CFG','PI') or im.itemType is null)</FilterExpression>
		<FilterExpression name="isDeleted" type="FIXED">im.isDeleted != 'Y'</FilterExpression>
	</Filters>

	<SearchParameters>
		<Text name="parentName" matchType="ILIKE"
			labelKey="functionalGroup.parentName"
			finderName="ParentFunctionalGroupName">
			<Expression>lower(pfg.name) like lower(:parentName)</Expression>
		</Text>
		<MultiText name="parentGroupNames" matchType="IEXACT"
			labelKey="functionalGroup.multipleParentGroupNames" rows="3"
			popupFinderName="ParentGroupFinder">
			<Expression>lower(pfg.name) in (:parentGroupNames)</Expression>
		</MultiText>
		<Text name="functionalGroupName" matchType="ILIKE"
			labelKey="functionalGroup.functionalGroupName"
			finderName="FunctionalGroupName">
			<Expression>lower(fg.name) like lower(:functionalGroupName)</Expression>
		</Text>
		<MultiText name="functionalGroupNames" matchType="IEXACT"
			labelKey="tam.exception.multiple_fg" rows="3"
			popupFinderName="FunctionalGroupFinder">
			<Expression>lower(fg.name) in (:functionalGroupNames)</Expression>
		</MultiText>
		<Text name="itemNumber" matchType="ILIKE"
			labelKey="item.itemNumber" finderName="ItemNumber">
			<Expression>lower(im.itemNumber) like lower(:itemNumber)</Expression>
		</Text>
		<MultiText name="itemNumbers" matchType="IEXACT"
			labelKey="item.multipleItemNumbers" rows="3">
			<Expression>lower(im.itemNumber) in (:itemNumbers)</Expression>
		</MultiText>
		<List name="actionDateGE" multiSelect="false"
			labelKey="cost.forecast.validation.report.date" required="false"
			initializer="com.scplatform.pcm.searchframework.initializer.FiscalMonthListInitializer">
			<Expression></Expression>
		</List>
		<List name="region" multiSelect="true" labelKey="tam.region" required="true"
			initializer="com.scplatform.pcm.searchframework.initializer.ForecastRegionListInitializer">
			<!-- Expression is not needed since the HQL will be formed in Action classes -->
			<Expression></Expression>
		</List>
	</SearchParameters>
</SearchFormDefinition>

=== bkumars22/SupplyChainPlatformProject/src/main/resources/config/search/SearchDefAuditHistory.xml
<?xml version="1.0" encoding="UTF-8"?>
<SearchFormDefinition name="SearchDefAuditHistory" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="SearchDefSchema.xsd">
    <Source>
		select a from PcmAuditHistory a
    </Source>
    
    <ExtractSource extractTemplateConfig="pcm.audit.downloads.config.paths" extractTemplate="AuditDownload">
		select a from PcmAuditHistory a
	</ExtractSource>
	
    <!-- Filter expressions are fixed and not used by the critera displayed to users
         They are used to construct fixed criteria based on if the named parameter
         is present in the list of parameter values passed to the query execution -->
    <Filters>        
      <FilterExpression name="targetKey" >:targetKey in elements(a.targetKeys)</FilterExpression>
      <FilterExpression name="targetType" >a.targetType = :targetType</FilterExpression>                          
    </Filters>
    <!-- Combining the date and order will force a sort that handles the lack of precision of timestamp -->
    <OrderBy fieldName="a.actionDate,a.actionOrder" colummName="actionDateGE" default="DESC"/>    
    <OrderBy fieldName="a.userId" colummName="userId"/>   
    <OrderBy fieldName="a.actionPerformed" colummName="actionPerformed"/>            
    <OrderBy fieldName="a.targetType"  colummName="targetType"/>
    <SearchParameters>
       <Text name="userId" matchType="LIKE" labelKey="audit.userId" finderName="UserId">
          <Expression>a.userId like :userId</Expression>
       </Text>
       <Text name="roleId" matchType="LIKE" labelKey="roleAdmin.roleId" finderName="RoleId">
          <Expression>lower(a.roleId) like lower(:roleId)</Expression>
       </Text>
       <Text name="actionPerformed" matchType="ILIKE" labelKey="audit.actionPerformed">
          <Expression>lower(a.actionPerformed) like lower(:actionPerformed)</Expression>
       </Text>
       <Date name="actionDateGE" matchType="GE" labelKey="audit.actionDateGE" dataType="DATE">
          <Expression>a.actionDate >= :actionDateGE</Expression>
       </Date>
       <Text name="comment" matchType="ILIKE" labelKey="audit.comment">
          <Expression>lower(a.comment) like lower(:comment)</Expression>
       </Text>
       <Text name="type" matchType="ILIKE" labelKey="audit.targetType">
          <Expression>lower(a.targetType) like lower(:type)</Expression>
       </Text>
		<Text name="lastLoadedByUser" matchType="ILIKE"
			labelKey="audit.lastLoadedByUser">
			<Expression>lower(a.lastLoadedByUser) like lower(:lastLoadedByUser)</Expression>
		</Text>
        <Date name="actionDateLT" matchType="LT" labelKey="audit.actionDateLT" dataType="DATE">
          <Expression>a.actionDate &lt; :actionDateLT</Expression>
       </Date>
		<List name="startYearPartition" multiValue="true" multiSelect= "false" labelKey = "functionalGroup.record_audit.partition.year" initializer="com.scplatform.pcm.searchframework.initializer.PartitionYearInitializer">
			<Expression>a.actionDate BETWEEN TO_TIMESTAMP(:startYearPartition0, 'YYYY-MM-DD') AND TO_TIMESTAMP(:startYearPartition1, 'YYYY-MM-DD')</Expression>
			<ListValue label="info.all" value=""/>
		</List>
    </SearchParameters>
</SearchFormDefinition>

=== bkumars22/SupplyChainPlatformProject/src/main/resources/config/search/SearchDefEnterpriseItemFinderForNewRebateRule.xml
<?xml version="1.0" encoding="UTF-8"?>
<SearchFormDefinition
	name="SearchDefEnterpriseItemFinderForNewRebateRule"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="SearchDefSchema.xsd">
	<Source queryType="SQL">
	SELECT IM.ITEM_KEY, IM.ITEM_IDENTIFIER, IM.ITEM_DESCRIPTION,  
		  BE.BUSINESS_ENTITY_NAME,
		 CASE
             WHEN IM.ITEM_TYPE='I' THEN 'ITEM'
                ELSE 'SUPPLIER'
        END  ITEMTYPE
     from ITEM_MASTER IM
	INNER JOIN BUSINESS_ENTITY BE on BE.BUSINESS_ENTITY_KEY=IM.BUSINESS_ENTITY_KEY
		 </Source>
	<OrderBy fieldName="ITEM_IDENTIFIER" default="ASC" />
	<SearchParameters>
		<Text name="itemNumber" matchType="LIKE"
			labelKey="popupfinder.EnterpriseItemFinderForNewRebateRule.label.ItemNumber">
			<Expression>upper(IM.ITEM_IDENTIFIER) like upper(:itemNumber)</Expression>
			<Property name="finderParams" value="itemType : I,S"/>
		</Text>
		 <List name="itemType" multiSelect="false" labelKey="popupfinder.EnterpriseItemFinderForNewRebateRule.label.ItemType">
			<Expression>IM.ITEM_TYPE in (:itemType)</Expression>
			<ListValue label="item.item" value="I" />
			<ListValue label="item.supplierItem" value="S" />
		</List>
		<Text name="business" matchType="ILIKE" labelKey="popupfinder.EnterpriseItemFinderForNewRebateRule.label.BEName"
			finderName="BusinessName">
			<Expression>lower(BE.BUSINESS_ENTITY_NAME) like lower(:business)</Expression>
		</Text>
		<MultiText name="itemNumbers" matchType="IEXACT"
			labelKey="popupfinder.EnterpriseItemFinderForNewRebateRule.label.multipleItemNumber" rows="3">
			<Expression>lower(IM.ITEM_IDENTIFIER) in (:itemNumbers)</Expression>
		</MultiText>
	</SearchParameters>
</SearchFormDefinition>

=== bkumars22/SupplyChainPlatformProject/src/main/resources/config/search/SearchDefCategoryMgmt.xml
<SearchFormDefinition name="SearchDefCategoryMgmt" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SearchDefSchema.xsd">
    <!-- NOTE:For the ItemManagementAction to work correctly,
        the first column returned in source must be i.itemKey
        so the allKeys option will work -->
    <Source keys="0">
		select c.categoryKey as categoryKey, 
		  c.categoryId as categoryId,
		  c.categoryName as categoryName,
          c.managedFlag as managedFlag,		  
          a.userId as user,
          a.responsibility.responsibilityKey as responsibility,          
          a.effectiveFromDate as effectiveFrom,
          a.effectiveToDate as effectiveTo					          
		  from ItemCategory c left outer join c.assignments a 		  
    </Source>

    <ExtractSource
            extractTemplateConfig="pcm.item.downloads.config.paths"
            extractTemplate="CommodityDownload"
            extractWriterClass="com.scplatform.pcm.util.commodityCode.commodityCodeExtractSSWriter">
        select c.categoryKey as categoryKey,
        c.categoryId as categoryId,
        c.categoryName as categoryName,
        c.managedFlag as managedFlag,
        a.userId as user,
        a.responsibility.responsibilityKey as responsibility,
        a.effectiveFromDate as effectiveFrom,
        a.effectiveToDate as effectiveTo
        from ItemCategory c left outer join c.assignments a
    </ExtractSource>

    <!-- Filter expressions are fixed and not used by the critera displayed to users
         They are used to construct fixed criteria based on if the named parameter
         is present in the list of parameter values passed to the query execution -->
    <Filters>                  
    </Filters>
    <OrderBy fieldName="c.categoryName" colummName="categoryName"/>    
    <OrderBy fieldName="c.managedFlag" colummName="managedFlag"/>            
    <SearchParameters>
       <Text name="categoryName" matchType="ILIKE" labelKey="item.category" finderName="ItemCategoryName">
          <Expression>lower(coalesce(c.categoryName,'N/A')) like lower(:categoryName)</Expression>
       </Text>
       <Text name="categoryIdentifier" matchType="ILIKE" labelKey="item.category.identifier" finderName="ItemCategoryIdentifier">
          <Expression>lower(coalesce(c.categoryId,'N/A')) like lower(:categoryIdentifier)</Expression>
       </Text>
       <Text name="user" matchType="LIKE" labelKey="as.user" finderName="AssignmentUserId">
          <Expression>a.userId like :user</Expression>
       </Text>       
       <List name="responsibility" multiSelect="false" labelKey="as.responsibility">
          <Expression>coalesce(a.responsibility.responsibilityKey,'N/A') = :responsibility</Expression>                     
          <ListValue label="info.all" value=""/>       
          <ListValue label="as.responsibility.OWNER" value="OWNER"/>          
          <ListValue label="as.notAssigned" value="N/A"/>
       </List>
       <List name="managedFlag" multiSelect="false" labelKey="mdm.managed"
          initializer="com.scplatform.pcm.searchframework.service.SearchListInitializer"
          initializerData="pcm.managedFlags">              
          <Expression>coalesce(c.managedFlag,'N/A') = :managedFlag</Expression>                     
          <ListValue label="info.all" value=""/>       
       </List>

       
    </SearchParameters>
</SearchFormDefinition>

=== bkumars22/SupplyChainPlatformProject/src/main/resources/config/search/SearchDefNoResponsibilityTAM.xml
<?xml version="1.0" encoding="UTF-8"?>
<SearchFormDefinition
        name="SearchDefNoResponsibilityTAMException"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="SearchDefSchema.xsd">
    <Source keys="0">
        select ta.id,fg.functionalGroupId,fg.name,fg.type,im.itemNumber,im.description,cat.categoryName ,im.eol,site.siteDescription,ta.lastChangedOn,ta.lastChangedBy
        from TAMAllocation ta
        inner join ta.site site
        inner join ta.functionalGroup fg
        inner join fg.functionalGroupItems im
        inner join im.assignments ia
        inner join im.categories cat

    </Source>
    <ExtractSource
            extractTemplateConfig="pcm.noResponsibility.tam.exception.downloads.config.paths"
            extractTemplate="NoRespnsibilityTAMExceptionDownloads"
            extractWriterClass="com.scplatform.pcm.util.tam.NoRespnsibilityTAMExceptionExtractSSWriter">

        select ta.id,fg.functionalGroupId,fg.name,fg.type,im.itemNumber,im.description,cat.categoryName ,im.eol,site.siteDescription,ta.lastChangedOn,ta.lastChangedBy
        from TAMAllocation ta
        inner join ta.site site
        inner join ta.functionalGroup fg
        inner join fg.functionalGroupItems im
        inner join im.assignments ia
        inner join im.categories cat 
     </ExtractSource>

    <Filters>
        <FilterExpression name="dateTypeFilter" type="FIXED">ta.lastChangedOn BETWEEN (:previousDate) AND (:currentDate) </FilterExpression>
        <FilterExpression name="multipleResponsibility" type="FIXED">im.itemKey NOT IN(select im.itemKey from im.assignments ia where ia.responsibility='PRODUCTION')</FilterExpression>
    </Filters>
    
    <GroupBy >
     ta.id,fg.functionalGroupId,fg.name,fg.type,im.itemNumber,im.description,cat.categoryName,im.eol,site.siteDescription,ta.lastChangedOn,ta.lastChangedBy
	</GroupBy>
    

    <OrderBy fieldName="fg.name" colummName="name" default="ASC" />
    <OrderBy fieldName="ta.lastChangedOn" colummName="updateDate" default="ASC" />

    <SearchParameters>
        <Date name="updateDate" labelKey="fg.noResponsiblity.exception.updateDate">
            <Expression>ta.lastChangedOn >= (:updateDate)</Expression>
        </Date>
        <Text name="functionalGroupName" matchType="ILIKE"
              labelKey="fg.noResponsiblity.exception.TAM"
              finderName="FunctionalGroupName">
            <Expression>lower(fg.name) like lower(:functionalGroupName)</Expression>
        </Text>

        <List name="itemEol"  multiSelect="false" dataType="boolean"
              labelKey="fg.noResponsiblity.exception.ItemEol">
            <Expression>coalesce(im.eol,false) = (:itemEol)</Expression>
            <ListValue label="noResponsibility.tam.info.blank" value=""/>
            <ListValue label="noResponsibility.tam.info.yes" value="true"/>
            <ListValue label="noResponsibility.tam.info.no" value="false"/>
        </List>

    </SearchParameters>
</SearchFormDefinition>
