=== bkumars22/SupplyChainPlatformProject/src/main/resources/config/search/SearchDefSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:jxb="http://java.sun.com/xml/ns/jaxb" jxb:version="2.0">
	<xs:annotation>
		<xs:documentation>Defines the schema for modeling a search page in
			the
			core PCM infrastructure.
		</xs:documentation>
	</xs:annotation>
	<xs:element name="SearchFormDefinition" type="SearchFormDefinitionType" />
	<xs:complexType name="SearchParametersType">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="Text" type="TextType" />
			<xs:element name="List" type="ListType" />
			<xs:element name="Date" type="DateType" />
			<xs:element name="MultiText" type="MultiTextType" />
		</xs:choice>
		<xs:attribute name="groupName" type="xs:string" default="DEFAULT" use="optional"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="SearchParameterType" abstract="true">
		<xs:sequence>
			<xs:element name="Expression" type="xs:string" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="Property" type="PropertyType"
				minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="DefaultExpressions" type="DefaultExpressionsType"
						minOccurs="0" maxOccurs="1" ></xs:element>
		</xs:sequence>
		<xs:attribute type="xs:string" name="name" use="optional" />
		<xs:attribute type="xs:string" name="labelKey" use="optional" />
		<xs:attribute type="xs:string" name="dataType" use="optional" />
		<xs:attribute type="xs:boolean" name="required" use="optional" />
		<xs:attribute name="includeIfPropTrue" type="xs:string" use="optional"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="ListType">
		<xs:complexContent>
			<xs:extension base="SearchParameterType">
				<xs:sequence>
					<xs:element name="ListValue" type="ListValueType"
						minOccurs="0" maxOccurs="unbounded">
					</xs:element>
				</xs:sequence>
				<xs:attribute type="xs:boolean" name="multiSelect"
					use="required" />
				<xs:attribute type="xs:string" name="initializer"
					use="optional" />
				<xs:attribute type="xs:string" name="initializerData"
					use="optional" />
				<xs:attribute name="dataFormat" type="xs:string"></xs:attribute>
				<xs:attribute name="checkIfTrue" type="xs:string"></xs:attribute>
				<xs:attribute type="xs:boolean" name="multiValue"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ListValueType">
		<xs:attribute type="xs:string" name="label" use="required" />
		<xs:attribute type="xs:string" name="value" use="required" />
	</xs:complexType>

	<xs:complexType name="OrderByType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="fieldName" use="optional">
					<xs:annotation>
						<xs:documentation>This is the name of the HQL column that will be
							used in the order
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute type="xs:string" name="colummName" use="optional">
					<xs:annotation>
						<xs:documentation>This is the name you have defined for the
							column. It is used by the UI to connect an order by widget to
							this clause
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute type="xs:string" name="default" use="optional">
					<xs:annotation>
						<xs:documentation>If default is set, it means this orderby is on
							and cannot be turned off by the user. They may change the
							direction.
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="GroupByType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="fieldName" use="optional">
					<xs:annotation>
						<xs:documentation>This is the name of the HQL column that will be
							used for Group By
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute type="xs:string" name="colummName" use="optional">
					<xs:annotation>
						<xs:documentation>This is the name you have defined for the
							column. It is used by the UI to connect a Group by widget to
							this clause
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="FilterExpressionType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="name" />
				<xs:attribute name="type" type="xs:string" use="optional"></xs:attribute>
				<xs:attribute name="dataType" type="xs:string" use="optional"></xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="TextType">
		<xs:complexContent>
			<xs:extension base="AbstractTextType">
				<xs:attribute type="xs:string" name="finderName"
					use="optional" />
				<xs:attribute name="matchType" use="optional"
					type="MatchType" />
				<xs:attribute name="checkIfTrue" type="xs:string"></xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="MultiTextType">
		<xs:complexContent>
			<xs:extension base="AbstractTextType">
				<xs:attribute type="MatchType" name="matchType" use="optional" />
				<xs:attribute type="xs:string" name="finderName" use="optional" />
				<xs:attribute type="xs:string" name="delimiter" use="optional"
					default=";" />
				<xs:attribute type="xs:int" name="rows" use="optional"
					default="3" />
				<xs:attribute name="popupFinderName" type="xs:string"></xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="SourceType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="keys" />
				<xs:attribute name="queryType" type="querySimpleType"  use="optional"/>
				<xs:attribute name="transformDefinition" type="xs:string"
					use="optional">
					<xs:annotation>
						<xs:documentation>Optional path to the transformation definition.
							The transformation can be applied to the result of the source
							query
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="FiltersType">
		<xs:sequence>
			<xs:element type="FilterExpressionType" name="FilterExpression"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SearchFormDefinitionType">
		<xs:sequence>
			<xs:element type="SourceType" name="Source" minOccurs="1"
				maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Models the select portion of a HQL statement
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="ExtractSourceType" name="ExtractSource"
				minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Extract source is used to generate an XSL file
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="FiltersType" name="Filters" minOccurs="0"
				maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Filter expressions are
						and not used by the
						critera displayed to users
						They are used to construct fixed
						criteria based on if the named
						parameter
						is present in the list of
						parameter values passed to the query
						execution
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="GroupByType" name="GroupBy" maxOccurs="unbounded"
				minOccurs="0" />
			<xs:element type="OrderByType" name="OrderBy" maxOccurs="unbounded"
				minOccurs="0" />
			<xs:element type="SearchParametersType" name="SearchParameters"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute type="xs:string" name="name" use="required" />
	</xs:complexType>

	<xs:complexType name="PropertyType">
		<xs:attribute name="name" type="xs:string"></xs:attribute>
		<xs:attribute name="value" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="DefaultExpressionsType">
		<xs:sequence>
			<xs:element type="ExprType"
				name="Expr" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ExprType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="name" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="ExtractSourceType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="extractWriterClass" type="xs:string"
					use="optional" />
				<xs:attribute name="extractWriterProps" type="xs:string"
					use="optional" />
				<xs:attribute name="transformDefinition" type="xs:string"
					use="optional">
					<xs:annotation>
						<xs:documentation>
							Optional path to the transformation
							definition.
							The transformation will be
							loaded and passed to the extract class.
							Standard extracts use this to transformt the
							result set from the
							extractSource.
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute name="extractTemplateConfig" type="xs:string">
				</xs:attribute>
				<xs:attribute name="extractTemplate" type="xs:string"></xs:attribute>
				<xs:attribute name="queryType" type="querySimpleType"  use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="AbstractTextType" abstract="true">
		<xs:complexContent>
			<xs:restriction base="SearchParameterType">
				<xs:sequence>
					<xs:element name="Expression" type="xs:string"
						maxOccurs="1" minOccurs="1" />
					<xs:element name="Property" type="PropertyType"
						minOccurs="0" maxOccurs="unbounded"></xs:element>
					<xs:element name="DefaultExpressions" type="DefaultExpressionsType"
						minOccurs="0" maxOccurs="1" ></xs:element>
				</xs:sequence>
				<xs:attribute name="dataType" type="xs:string" fixed="TEXT" />
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="DateType">
		<xs:complexContent>
			<xs:extension base="AbstractDateType">
				<xs:attribute name="matchType" type="MatchType"></xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>


	<xs:complexType name="AbstractDateType" abstract="true">
		<xs:complexContent>
			<xs:restriction base="SearchParameterType">
				<xs:sequence>
					<xs:element name="Expression" type="xs:string"
						maxOccurs="1" minOccurs="1" />
					<xs:element name="Property" type="PropertyType"
						minOccurs="0" maxOccurs="unbounded">
					</xs:element>
				</xs:sequence>
				<xs:attribute name="dataType" type="xs:string" fixed="DATE"/>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>

	<xs:simpleType name="MatchType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="EXACT"></xs:enumeration>
			<xs:enumeration value="IEXACT"></xs:enumeration>
			<xs:enumeration value="LIKE"></xs:enumeration>
			<xs:enumeration value="ILIKE"></xs:enumeration>
			<xs:enumeration value="GE"></xs:enumeration>
			<xs:enumeration value="GT"></xs:enumeration>
			<xs:enumeration value="LE"></xs:enumeration>
			<xs:enumeration value="LT"></xs:enumeration>
			<xs:enumeration value="IN"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="querySimpleType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="SQL"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== bkumars22/SupplyChainPlatformProject/src/main/resources/config/search/SearchDefTAMDeleteDownload.xml
<SearchFormDefinition name="SearchDefTAMDeleteDownload" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SearchDefSchema.xsd">
	<Source keys="0" >
	select fg,site from FunctionalGroup as fg,Site as site
	left join site.siteDetail as siteDetail
	</Source>
	<ExtractSource  extractWriterClass="com.scplatform.pcm.util.tam.TAMDeleteTemplateDownloadSSWriter">
	select fg.name,fg.type,site.siteType, site.siteDescription from FunctionalGroup as fg,Site as site
	left join site.siteDetail as siteDetail
	</ExtractSource>
	<Filters>
		<FilterExpression name="siteTypeFilter" type="FIXED">(site.siteType in ('GLOBAL','REGION','SITE'))</FilterExpression>
		<FilterExpression name="onlyCFG" type="FIXED">fg.type = 'CFG'</FilterExpression>
	</Filters>

	<OrderBy fieldName="fg.name" colummName="name" default="DESC" />
	<OrderBy fieldName="site.siteDescription" colummName="name" default="ASC" />
	
	<SearchParameters>
		<Text name="itemNumber" matchType="ILIKE"
			labelKey="tam.search.itemNumber" finderName="ItemNumber">
			<Expression>exists (select 1 from fg.functionalGroupItems im where lower(im.itemNumber) like lower(:itemNumber))</Expression>
			<Property name="finderParams" value="itemType : 'I,S,M,PI'"/>
		</Text>
		<MultiText name="itemNumbers" matchType="IEXACT"
			labelKey="tam.search.multipleItemNumbers" rows="3"
			popupFinderName="EnterpriseItemFinder">
			<Expression>exists (select 1 from fg.functionalGroupItems im where lower(im.itemNumber) in (:itemNumbers))</Expression>
		</MultiText>	
		<Text name="functionalGroupName" matchType="ILIKE"
			labelKey="tam.search.functionalGroupName"
			finderName="FunctionalGroupName">
			<Expression>lower(fg.name) like lower(:functionalGroupName)</Expression>
		</Text>
		<MultiText name="groupNames" matchType="IEXACT"
			labelKey="tam.search.multipleGroupNames" rows="3"
			popupFinderName="CFG_FunctionalGroupFinder">
			<Expression>lower(fg.name) in (:groupNames)</Expression>
		</MultiText>
		<Text name="site" matchType="ILIKE" labelKey="tam.search.site"
			finderName="Site">
			<Expression>lower(site.siteDescription) like lower(:site)</Expression>
			<Property name="finderParams"
				value="businessType:1,siteType:'GLOBAL,SITE,REGION'" />
		</Text>
		<MultiText name="sites" matchType="IEXACT"
			labelKey="tam.search.multiple_site" rows="3"
			popupFinderName="EnterpriseCostSiteFinder">
			<Expression>lower(site.siteDescription) in (:sites)</Expression>
		</MultiText>
		<List name="groupType" multiSelect="false"
			labelKey="functionalGroup.groupType">
			<Expression>upper(fg.type) = upper(:groupType)
          </Expression>
			<ListValue label="functionalGroup.CFG" value="CFG" />
		</List>								
		<List name="supplierAllocationExist" multiSelect="false"
			labelKey="tam.search.supplier_exist">
			<Expression>
			{VALUE} (select 1
					from TAMAllocation tam
					left join tam.supplierAllocations tsa
					where tam.functionalGroup = fg
					and tam.site = site
					and tsa.endDate >= trunc(current_date())
					and tsa.allocation > 0)
			</Expression>
			<ListValue label="info.all" value="" />
			<ListValue label="info.yes" value="exists" />
			<ListValue label="info.no" value="not exists" />
		</List>
		<List name="itemAllocationExist" multiSelect="false"
			labelKey="tam.search.item_exist">
			<Expression>
			{VALUE} (select 1
					from TAMAllocation tam
					left join tam.supplierAllocations tsa
					left join tsa.itemAllocations tia
					where tam.functionalGroup = fg
					and tam.site = site
					and tsa.endDate >= trunc(current_date())
					and tia.allocation > 0)
			</Expression>
			<ListValue label="info.all" value="" />
			<ListValue label="info.yes" value="exists" />
			<ListValue label="info.no" value="not exists" />
		</List>				
	</SearchParameters>
</SearchFormDefinition>

=== bkumars22/SupplyChainPlatformProject/src/main/resources/config/search/SearchDefCostRecordXLOBFGFlexAttributeFinder.xml
<?xml version="1.0" encoding="UTF-8"?>
<SearchFormDefinition
	name="CostRecordXLOBFGFlexAttributeFinder"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="SearchDefSchema.xsd">
	<Source>
		select count(*), fg.name from PcmCostRecord cr join FunctionalGroup fg on cr.numberAttribute1 = fg.functionalGroupId
    </Source>
	<Filters>
		<FilterExpression name="costTypeFilter" type="FIXED">cr.costType.costTypeKey = 'XWAP'</FilterExpression>
		<FilterExpression name="flexAttrFilter" type="FIXED">cr.numberAttribute1 != -1</FilterExpression>
		<FilterExpression name="fgTypeFilter" type="FIXED">fg.type = 'XLOB'</FilterExpression>
	</Filters>
	<GroupBy>
  		fg.name
    </GroupBy>
    <OrderBy fieldName="fg.name" colummName="name" />
	<SearchParameters>
		<Text name="name" matchType="LIKE"
			labelKey="flex.cost.numberAttribute1">
			<Expression>upper(fg.name) like upper(:name)</Expression>
		</Text>
	</SearchParameters>
</SearchFormDefinition>

=== bkumars22/SupplyChainPlatformProject/src/main/resources/config/search/SearchDefItem.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- PLEASE READ =========== This search def is really for Item AVL search 
	tied to the Workflow Item AVL . Since this was originally the Item search 
	we are not changing the links. The new exclusive Item search is named *ItemOnly -->

<SearchFormDefinition name="SearchDefItem"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="SearchDefSchema.xsd">
	<Source>
		select im, be, avl, sup, si
        from Item im 
        join im.businessEntity be 
        left outer join im.amls aml
		left outer join im.avls avl 
		left outer join avl.supplier sup 
		left outer join avl.supplierItem si
		left outer join im.categories cat
    </Source>

	<ExtractSource extractTemplateConfig="pcm.item.downloads.config.paths"
		extractTemplate="ItemAVLDownload" extractWriterClass="com.scplatform.pcm.util.item.ItemAVLExtractSSWriter">
		  select im, cat.categoryName as CommodityName, si, avl
          from Item im
          join im.businessEntity be
          left outer join im.amls aml
          left outer join im.avls avl 
		  left outer join avl.supplier sup 
		  left outer join avl.supplierItem si
		  left outer join im.categories cat
</ExtractSource>

	<!-- Filter expressions are fixed and not used by the criteria displayed 
		to users They are used to construct fixed criteria based on if the named 
		parameter is present in the list of parameter values passed to the query 
		execution -->
	<Filters>
		<FilterExpression name="supplierItemRequired">si.itemKey is not null</FilterExpression>
		<FilterExpression name="isDeleted" type="FIXED">im.isDeleted != 'Y'</FilterExpression>
		<FilterExpression name="excludeCFGType" type="FIXED">upper(im.itemType) != 'CFG'</FilterExpression>
		<FilterExpression name="objectKey">im.itemKey in (:objectKey)</FilterExpression>
	</Filters>
	<OrderBy fieldName="im.itemNumber" colummName="itemNumber" />
	<OrderBy fieldName="im.description" colummName="itemDescription" />
	<OrderBy fieldName="be.businessEntityName" colummName="businessName" />
	<OrderBy fieldName="mfg.businessEntityName" colummName="mfgName" />
	<OrderBy fieldName="sup.businessEntityName" colummName="supName" />
	<SearchParameters>
		<Text name="itemNumber" matchType="ILIKE" labelKey="item.itemNumber"
			finderName="ItemNumberWithOutCFGType">
			<Expression>lower(im.itemNumber) like lower(:itemNumber)</Expression>
		</Text>
		<Text name="businessName" matchType="ILIKE" labelKey="item.businessName"
			finderName="BusinessName">
			<Expression>lower(be.businessEntityName) like lower(:businessName)</Expression>
		</Text>
		<Text name="itemDescription" matchType="ILIKE" labelKey="item.itemDescription">
			<Expression>lower(im.description) like lower(:itemDescription)</Expression>
		</Text>
		<MultiText name="itemNumbers" matchType="IEXACT"
			labelKey="item.multipleItemNumbers" rows="3" popupFinderName="EnterpriseItemFinder">
			<Expression>lower(im.itemNumber) in (:itemNumbers)</Expression>
		</MultiText>
		<List name="itemType" multiSelect="true" labelKey="item.type">
			<Expression>im.itemType in (:itemType)</Expression>
			<ListValue label="item.item" value="I" />
			<ListValue label="item.supplierItem" value="S" />
			<ListValue label="item.mfgItem" value="M" />
			<ListValue label="item.phantomItem" value="PI" />
		</List>

		<List name="topLevel" multiSelect="false" dataType="boolean"
			labelKey="item.isTopLevel">
			<Expression>coalesce(im.isTopLevel,false) = :topLevel</Expression>
			<ListValue label="info.blank" value="" />
			<ListValue label="info.no" value="false" />
 			<ListValue label="info.yes" value="true" />
		</List>
		<Text name="productFamily" matchType="ILIKE" labelKey="item.productFamily">
			<Expression>lower(im.productFamily) like lower(:productFamily)</Expression>
		</Text>
		<Text name="itemClassification" matchType="ILIKE" labelKey="item.classification">
			<Expression>lower(im.itemClassification) like lower(:itemClassification)</Expression>
		</Text>
		<Text name="platformName" matchType="ILIKE" labelKey="item.platform"
			finderName="PlatformName">
			<Expression>exists (select 1 from im.platforms ip where lower(ip.platformName) like lower(:platformName))</Expression>
		</Text>
		<List name="isAssigned" multiSelect="false" labelKey="as.assigned">
			<Expression>case when :owner is null and :user is null and {VALUE} (select 1 from ItemAssignment where item = im) then 1
          when :owner is not null or :user is not null then 1
          else 0
          end = 1
          </Expression>
			<ListValue label="info.all" value="" />
			<ListValue label="info.yes" value="exists" />
			<ListValue label="info.no" value="not exists" />
		</List>
		<List name="owner" multiSelect="false" labelKey="as.responsibility"
			initializer="com.scplatform.pcm.searchframework.initializer.ResponsibilityListInitializer"
			initializerData="responsibilityType:['I']">
			<Expression>case when (:isAssigned is null or :isAssigned = 'exists') and exists (select 1 from im.assignments a where lower(a.responsibility) like lower(:owner) and (:user is null or lower(a.userId) like lower(:user))) then 1
		  when :isAssigned = 'not exists' and not exists (select 1 from im.assignments a where lower(a.responsibility) = lower(:owner) and (:user is null or lower(a.userId) like lower(:user))) then 1
		  else 0
		  end = 1
	      </Expression>
			<ListValue label="info.all" value="" />
		</List>
				<List name="regions" multiSelect="true" labelKey="as.region"
          initializer="com.scplatform.pcm.searchframework.initializer.ResponsibilityRegionListInitializer">
          <Expression>exists (select 1 from im.assignments a left join a.regionalResponsibility rs left join rs.site st where st.siteKey in (:regions))</Expression>
       	</List>
		<Text name="user" matchType="ILIKE" labelKey="as.user"
			finderName="ItemOwner">
			<Expression>case when :owner is not null then 1
		  when (:isAssigned is null or :isAssigned = 'exists') and exists (select 1 from im.assignments a where lower(a.userId) like lower(:user)) then 1
		  when :isAssigned = 'not exists' and not exists (select 1 from im.assignments a where lower(a.userId) like lower(:user)) then 1
		  else 0
		  end = 1
          </Expression>
		</Text>
		<Text name="categoryName" matchType="ILIKE" labelKey="item.categoryName"
			finderName="ItemCategoryName">
			<Expression>lower(coalesce(cat.categoryName,'N/A')) like lower(:categoryName)</Expression>
		</Text>
		<Text name="supplierItemNumber" matchType="ILIKE"
			labelKey="item.supplierItemNumber">
			<Expression>lower(si.itemNumber) like lower(:supplierItemNumber)</Expression>
			<DefaultExpressions>
            <Expr name="=NULL">si.itemNumber is null</Expr>
            <Expr name="!=NULL">si.itemNumber is not null</Expr>
            <Expr name="=EMPTY">si.itemNumber is null</Expr>
            <Expr name="!=EMPTY">si.itemNumber is not null</Expr>
            <Expr name="!=">si.itemNumber != :supplierItemNumber</Expr>
          </DefaultExpressions>
		</Text>
		<Text name="supplierName" matchType="ILIKE" labelKey="item.supplierName"
			finderName="SupplierName">
			<Expression>lower(sup.businessEntityName) like lower(:supplierName)</Expression>
			<DefaultExpressions>
            <Expr name="=NULL">sup.businessEntityName is null</Expr>
            <Expr name="!=NULL">sup.businessEntityName is not null</Expr>
            <Expr name="=EMPTY">sup.businessEntityName is null</Expr>
            <Expr name="!=EMPTY">sup.businessEntityName is not null</Expr>
            <Expr name="!=">sup.businessEntityName != :supplierName</Expr>
          </DefaultExpressions>
		</Text>
		<MultiText name="categoryNames" matchType="IEXACT"
			labelKey="item.multipleCategoryNames" rows="3" popupFinderName="ItemCategoryFinder">
			<Expression>lower(coalesce(cat.categoryName,'N/A')) in (:categoryNames)</Expression>
		</MultiText>
        <Text name="dataSource" matchType="ILIKE" labelKey="item.dataSource" finderName="dataSource">
          <Expression>lower(im.dataSource) like lower(:dataSource)</Expression>
       </Text>
        <List name="eolType" multiSelect="false" labelKey="item.eol.state" initializer="com.scplatform.pcm.searchframework.initializer.ItemEOLTypeListInitializer">
            <Expression> im.eolType = :eolType
            </Expression>
        </List>
	</SearchParameters>
</SearchFormDefinition>
