=== bkumars22/SupplyChainPlatformProject/src/main/resources/config/search/SearchDefSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:jxb="http://java.sun.com/xml/ns/jaxb" jxb:version="2.0">
	<xs:annotation>
		<xs:documentation>Defines the schema for modeling a search page in
			the
			core PCM infrastructure.
		</xs:documentation>
	</xs:annotation>
	<xs:element name="SearchFormDefinition" type="SearchFormDefinitionType" />
	<xs:complexType name="SearchParametersType">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="Text" type="TextType" />
			<xs:element name="List" type="ListType" />
			<xs:element name="Date" type="DateType" />
			<xs:element name="MultiText" type="MultiTextType" />
		</xs:choice>
		<xs:attribute name="groupName" type="xs:string" default="DEFAULT" use="optional"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="SearchParameterType" abstract="true">
		<xs:sequence>
			<xs:element name="Expression" type="xs:string" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="Property" type="PropertyType"
				minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="DefaultExpressions" type="DefaultExpressionsType"
						minOccurs="0" maxOccurs="1" ></xs:element>
		</xs:sequence>
		<xs:attribute type="xs:string" name="name" use="optional" />
		<xs:attribute type="xs:string" name="labelKey" use="optional" />
		<xs:attribute type="xs:string" name="dataType" use="optional" />
		<xs:attribute type="xs:boolean" name="required" use="optional" />
		<xs:attribute name="includeIfPropTrue" type="xs:string" use="optional"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="ListType">
		<xs:complexContent>
			<xs:extension base="SearchParameterType">
				<xs:sequence>
					<xs:element name="ListValue" type="ListValueType"
						minOccurs="0" maxOccurs="unbounded">
					</xs:element>
				</xs:sequence>
				<xs:attribute type="xs:boolean" name="multiSelect"
					use="required" />
				<xs:attribute type="xs:string" name="initializer"
					use="optional" />
				<xs:attribute type="xs:string" name="initializerData"
					use="optional" />
				<xs:attribute name="dataFormat" type="xs:string"></xs:attribute>
				<xs:attribute name="checkIfTrue" type="xs:string"></xs:attribute>
				<xs:attribute type="xs:boolean" name="multiValue"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ListValueType">
		<xs:attribute type="xs:string" name="label" use="required" />
		<xs:attribute type="xs:string" name="value" use="required" />
	</xs:complexType>

	<xs:complexType name="OrderByType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="fieldName" use="optional">
					<xs:annotation>
						<xs:documentation>This is the name of the HQL column that will be
							used in the order
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute type="xs:string" name="colummName" use="optional">
					<xs:annotation>
						<xs:documentation>This is the name you have defined for the
							column. It is used by the UI to connect an order by widget to
							this clause
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute type="xs:string" name="default" use="optional">
					<xs:annotation>
						<xs:documentation>If default is set, it means this orderby is on
							and cannot be turned off by the user. They may change the
							direction.
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="GroupByType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="fieldName" use="optional">
					<xs:annotation>
						<xs:documentation>This is the name of the HQL column that will be
							used for Group By
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute type="xs:string" name="colummName" use="optional">
					<xs:annotation>
						<xs:documentation>This is the name you have defined for the
							column. It is used by the UI to connect a Group by widget to
							this clause
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="FilterExpressionType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="name" />
				<xs:attribute name="type" type="xs:string" use="optional"></xs:attribute>
				<xs:attribute name="dataType" type="xs:string" use="optional"></xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="TextType">
		<xs:complexContent>
			<xs:extension base="AbstractTextType">
				<xs:attribute type="xs:string" name="finderName"
					use="optional" />
				<xs:attribute name="matchType" use="optional"
					type="MatchType" />
				<xs:attribute name="checkIfTrue" type="xs:string"></xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="MultiTextType">
		<xs:complexContent>
			<xs:extension base="AbstractTextType">
				<xs:attribute type="MatchType" name="matchType" use="optional" />
				<xs:attribute type="xs:string" name="finderName" use="optional" />
				<xs:attribute type="xs:string" name="delimiter" use="optional"
					default=";" />
				<xs:attribute type="xs:int" name="rows" use="optional"
					default="3" />
				<xs:attribute name="popupFinderName" type="xs:string"></xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="SourceType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="keys" />
				<xs:attribute name="queryType" type="querySimpleType"  use="optional"/>
				<xs:attribute name="transformDefinition" type="xs:string"
					use="optional">
					<xs:annotation>
						<xs:documentation>Optional path to the transformation definition.
							The transformation can be applied to the result of the source
							query
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="FiltersType">
		<xs:sequence>
			<xs:element type="FilterExpressionType" name="FilterExpression"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SearchFormDefinitionType">
		<xs:sequence>
			<xs:element type="SourceType" name="Source" minOccurs="1"
				maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Models the select portion of a HQL statement
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="ExtractSourceType" name="ExtractSource"
				minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Extract source is used to generate an XSL file
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="FiltersType" name="Filters" minOccurs="0"
				maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Filter expressions are
						and not used by the
						critera displayed to users
						They are used to construct fixed
						criteria based on if the named
						parameter
						is present in the list of
						parameter values passed to the query
						execution
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="GroupByType" name="GroupBy" maxOccurs="unbounded"
				minOccurs="0" />
			<xs:element type="OrderByType" name="OrderBy" maxOccurs="unbounded"
				minOccurs="0" />
			<xs:element type="SearchParametersType" name="SearchParameters"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute type="xs:string" name="name" use="required" />
	</xs:complexType>

	<xs:complexType name="PropertyType">
		<xs:attribute name="name" type="xs:string"></xs:attribute>
		<xs:attribute name="value" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="DefaultExpressionsType">
		<xs:sequence>
			<xs:element type="ExprType"
				name="Expr" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ExprType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="name" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="ExtractSourceType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="extractWriterClass" type="xs:string"
					use="optional" />
				<xs:attribute name="extractWriterProps" type="xs:string"
					use="optional" />
				<xs:attribute name="transformDefinition" type="xs:string"
					use="optional">
					<xs:annotation>
						<xs:documentation>
							Optional path to the transformation
							definition.
							The transformation will be
							loaded and passed to the extract class.
							Standard extracts use this to transformt the
							result set from the
							extractSource.
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute name="extractTemplateConfig" type="xs:string">
				</xs:attribute>
				<xs:attribute name="extractTemplate" type="xs:string"></xs:attribute>
				<xs:attribute name="queryType" type="querySimpleType"  use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="AbstractTextType" abstract="true">
		<xs:complexContent>
			<xs:restriction base="SearchParameterType">
				<xs:sequence>
					<xs:element name="Expression" type="xs:string"
						maxOccurs="1" minOccurs="1" />
					<xs:element name="Property" type="PropertyType"
						minOccurs="0" maxOccurs="unbounded"></xs:element>
					<xs:element name="DefaultExpressions" type="DefaultExpressionsType"
						minOccurs="0" maxOccurs="1" ></xs:element>
				</xs:sequence>
				<xs:attribute name="dataType" type="xs:string" fixed="TEXT" />
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="DateType">
		<xs:complexContent>
			<xs:extension base="AbstractDateType">
				<xs:attribute name="matchType" type="MatchType"></xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>


	<xs:complexType name="AbstractDateType" abstract="true">
		<xs:complexContent>
			<xs:restriction base="SearchParameterType">
				<xs:sequence>
					<xs:element name="Expression" type="xs:string"
						maxOccurs="1" minOccurs="1" />
					<xs:element name="Property" type="PropertyType"
						minOccurs="0" maxOccurs="unbounded">
					</xs:element>
				</xs:sequence>
				<xs:attribute name="dataType" type="xs:string" fixed="DATE"/>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>

	<xs:simpleType name="MatchType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="EXACT"></xs:enumeration>
			<xs:enumeration value="IEXACT"></xs:enumeration>
			<xs:enumeration value="LIKE"></xs:enumeration>
			<xs:enumeration value="ILIKE"></xs:enumeration>
			<xs:enumeration value="GE"></xs:enumeration>
			<xs:enumeration value="GT"></xs:enumeration>
			<xs:enumeration value="LE"></xs:enumeration>
			<xs:enumeration value="LT"></xs:enumeration>
			<xs:enumeration value="IN"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="querySimpleType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="SQL"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== bkumars22/SupplyChainPlatformProject/src/main/resources/config/search/SearchDefCostPendingAlert.xml
<?xml version="1.0" encoding="UTF-8"?>
<SearchFormDefinition name="SearchDefCostPendingAlert" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="SearchDefSchema.xsd">
    <Source>
		select a from Alert a
    </Source>

    <!-- Filter expressions are fixed and not used by the critera displayed to users
         They are used to construct fixed criteria based on if the named parameter
         is present in the list of parameter values passed to the query execution -->
    <Filters>

    </Filters>
    <OrderBy fieldName="a.created" colummName="created"/>

    <SearchParameters>
    	<List name="state" multiSelect="false" labelKey="alert.state">
       		<Expression>a.state = '{VALUE}'</Expression>
			<ListValue value="ACTIVE" label="alert.state.active"/>
			<ListValue value="DISMISSED" label="alert.state.dismissed"/>
       	</List>
    	<Text name="summary" matchType="ILIKE" labelKey="alert.shortSummary" finderName="alertShortSummary" >
		<Expression>lower(a.shortSummary) like lower(:summary)</Expression>
    	</Text>
      	<Date name="fromDate" labelKey="alert.generation.date.from" matchType="GE">
          <Expression>a.created >= :fromDate</Expression>
      	</Date>
      	<Date name="toDate" labelKey="alert.generation.date.to" matchType="LE">
          <Expression>a.created  &lt;= :toDate</Expression>
      	</Date>
      	<Date name="expirationFromDate" labelKey="alert.expiration.date.from" matchType="GE">
          <Expression>a.expirationDate >= :expirationFromDate</Expression>
      	</Date>
      	<Date name="expirationToDate" labelKey="alert.expiration.date.to" matchType="LE">
          <Expression>a.expirationDate &lt;= :expirationToDate</Expression>
      	</Date>
      	<List name="responsibility" multiSelect="false" labelKey="alert.responsibility"
          initializer="com.scplatform.pcm.searchframework.initializer.ResponsibilityListInitializer"
          initializerData="responsibilityType:['I']">
		  <Expression>a.stringAttribute6 = :responsibility</Expression>
          <ListValue label="info.all" value=""/>
      	</List>
       	<Text name="itemNumber" matchType="ILIKE" labelKey="alert.item" finderName="AlertItem">
          <Expression>lower(a.stringAttribute1) like lower(:itemNumber)</Expression>
       	</Text>
       	<Text name="updateBy" matchType="ILIKE" labelKey="alert.updateBy" finderName="alertUpdateBy">
          <Expression>lower(a.stringAttribute1) like lower(:updateBy)</Expression>
       	</Text>

       	 <List name="costType" multiSelect="true" labelKey="cr.costType" required="false"
          initializer="com.test.repository.pcm.util.search.CostTypeListInitializer">
          <Expression>a.stringAttribute7 in (:costType)</Expression>
       </List>

       <List name="status" multiSelect="true" labelKey="cr.status"
          initializer="com.scplatform.pcm.searchframework.initializer.SMStateInitializer"
          initializerData="Sourcing">
          <Expression>a.stringAttribute8 in (:status)</Expression>
       </List>
       <Text name="supplierName" matchType="ILIKE" labelKey="item.supplierName" finderName="SupplierName">
          <Expression>lower(a.stringAttribute2) like lower(:supplierName)</Expression>
       </Text>

       <Text name="toSite" matchType="ILIKE" labelKey="sl.toSite" finderName="Site">
          <Expression>lower(a.stringAttribute4) like lower(:toSite)</Expression>
          <Property name="finderParams" value="businessType:1,siteType:'GLOBAL,SITE,REGION'"/>
       </Text>
        <Date name="effectiveDate" labelKey="label.effective_date" matchType="GT">
          <Expression>(a.dateAttribute1 is null or trunc(a.dateAttribute1) > trunc(:effectiveDate))</Expression>
       </Date>
       <Date name="expireDate" labelKey="label.expire_date" matchType="LT">
          <Expression>(trunc(a.dateAttribute2) &lt; trunc(:expireDate))</Expression>
       </Date>
    </SearchParameters>
</SearchFormDefinition>

=== bkumars22/SupplyChainPlatformProject/src/main/resources/config/search/SearchDefCostExceptionAuditHistory.xml
<?xml version="1.0" encoding="UTF-8"?>
<SearchFormDefinition name="SearchDefCostExceptionAuditHistory" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                      xsi:noNamespaceSchemaLocation="SearchDefSchema.xsd">
    <Source>
        select a.key as key,
        a.actionDate as actionDate,
        a.userId as userId,
        a.roleId as roleId,
        a.actionPerformed as actionPerformed,
        a.comment as comment,
        a.targetType as targetType
        from PcmAuditHistory a, PcmAuditHistoryTarget t
    </Source>

    <ExtractSource extractTemplateConfig="pcm.audit.downloads.config.paths" extractTemplate="AuditDownload">
        select a from PcmAuditHistory a, PcmAuditHistoryTarget t
    </ExtractSource>

    <Filters>
        <FilterExpression name="targetType" type="FIXED" >a.targetType = 'CostException'</FilterExpression>
        <FilterExpression name="targetKey" >t.targetId.auditKey = a.key and t.targetId.targetKey = :targetKey</FilterExpression>
    </Filters>

    <OrderBy fieldName="a.actionDate,a.actionOrder" colummName="actionDateGE" default="DESC"/>
    <OrderBy fieldName="a.userId" colummName="userId"/>
    <OrderBy fieldName="a.actionPerformed" colummName="actionPerformed"/>
    <OrderBy fieldName="a.targetType"  colummName="targetType"/>
    <SearchParameters>
        <Text name="userId" matchType="LIKE" labelKey="audit.userId" finderName="UserId">
            <Expression>a.userId like :userId</Expression>
        </Text>
        <Text name="roleId" matchType="LIKE" labelKey="roleAdmin.roleId" finderName="RoleId">
            <Expression>lower(a.roleId) like lower(:roleId)</Expression>
        </Text>
        <Text name="actionPerformed" matchType="ILIKE" labelKey="audit.actionPerformed">
            <Expression>lower(a.actionPerformed) like lower(:actionPerformed)</Expression>
        </Text>
        <Date name="actionDateGE" matchType="GE" labelKey="audit.actionDateGE">
            <Expression>a.actionDate >= :actionDateGE</Expression>
        </Date>
        <Text name="comment" matchType="ILIKE" labelKey="audit.comment">
            <Expression>lower(a.comment) like lower(:comment)</Expression>
        </Text>
        <Text name="type" matchType="ILIKE" labelKey="audit.targetType">
            <Expression>lower(a.targetType) like lower(:type)</Expression>
        </Text>
        <Date name="actionDateLT" matchType="LT" labelKey="audit.actionDateLT">
            <Expression>a.actionDate &lt; :actionDateLT</Expression>
        </Date>
        <List name="startYearPartition" multiValue="true" multiSelect= "false" labelKey = "functionalGroup.record_audit.partition.year" initializer="com.scplatform.pcm.searchframework.initializer.PartitionYearInitializer">
			<Expression>a.actionDate BETWEEN TO_TIMESTAMP(:startYearPartition0, 'YYYY-MM-DD') AND TO_TIMESTAMP(:startYearPartition1, 'YYYY-MM-DD')</Expression>
			<ListValue label="info.all" value=""/>
		</List>
    </SearchParameters>
</SearchFormDefinition>

=== bkumars22/SupplyChainPlatformProject/src/main/resources/config/search/SearchDefItemMgmt.xml
<SearchFormDefinition name="SearchDefItemMgmt" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SearchDefSchema.xsd">
    <!-- NOTE:For the ItemManagementAction to work correctly,
        the first column returned in source must be im.itemKey
        so the allKeys option will work -->
    <Source keys="0">
		select im.itemKey as itemKey, 
		  im.itemNumber as itemNumber,
		  im.description as itemDescription,
          be as businessEntity,          
          function('TRUNC', current_date - cast(im.insertDate as date)) as daysOld,
          a.userId||' - '||r.responsibilityKey||''||a.region as owner,
          cat.categoryName as categoryName,
          im.managedFlag as managedFlag,
          cat.managedFlag as catManagedFlag,
          im.itemKey||'|'||a.userId||'|'||r.responsibilityKey as multiKey,
          im.itemType as itemType,
          im.itemExternalId as itemExternalId,
          im.dataSource as dataSource,
          a.lastRevChangeDate as lastRevChangeDate
		  from Item im join im.businessEntity be 
		  left outer join im.categories cat
		  left outer join im.assignments a with a.responsibility.responsibilityKey != 'BUYER'
		  left outer join a.responsibility r
    </Source>
    <!-- Filter expressions are fixed and not used by the critera displayed to users
         They are used to construct fixed criteria based on if the named parameter
         is present in the list of parameter values passed to the query execution -->
    <Filters>                  
      <FilterExpression name="isDeleted" type="FIXED">im.isDeleted != 'Y'</FilterExpression>
      <FilterExpression name="objectKey">im.itemKey in (:objectKey)</FilterExpression>
  	  <FilterExpression name="categoryNameExact">lower(coalesce(cat.categoryName,'N/A')) = lower(:categoryNameExact)</FilterExpression>
    </Filters>
    <OrderBy fieldName="im.itemNumber" colummName="itemNumber"/>
    <OrderBy fieldName="im.description" colummName="itemDescription"/>
    <OrderBy fieldName="a.userId" colummName="user"/>
    <OrderBy fieldName="cat.categoryName" colummName="categoryName"/>
    <OrderBy fieldName="be.businessEntityName" colummName="business"/>
    <OrderBy fieldName="im.managedFlag" colummName="managedFlag"/>        
    <OrderBy fieldName="8" colummName="daysOld"/>    
    <SearchParameters>
    
    <!-- Don't change the Search feld sequence. If changes required, change the hard coded ID in jsp -->
       <Text name="itemNumber" matchType="ILIKE" labelKey="item.itemNumber" finderName="ItemNumber">
          <Expression>lower(im.itemNumber) like lower(:itemNumber)</Expression>
       </Text>
       <Text name="business" matchType="ILIKE" labelKey="item.businessName" finderName="BusinessName">
          <Expression>lower(be.businessEntityName) like lower(:business)</Expression>
          <DefaultExpressions>
            <Expr name="=NULL">be.businessEntityName is null</Expr>
            <Expr name="!=NULL">be.businessEntityName is not null</Expr>
            <Expr name="=EMPTY">be.businessEntityName is null</Expr>
            <Expr name="!=EMPTY">be.businessEntityName is not null</Expr>
            <Expr name="!=">be.businessEntityName != :business</Expr>
          </DefaultExpressions>
       </Text>       
       <Text name="categoryName" matchType="ILIKE" labelKey="item.category" finderName="ItemCategoryName">
          <Expression>lower(coalesce(cat.categoryName,'N/A')) like lower(:categoryName)</Expression>
          <DefaultExpressions>
            <Expr name="=NULL">cat.categoryName is null</Expr>
            <Expr name="!=NULL">cat.categoryName is not null</Expr>
            <Expr name="=EMPTY">cat.categoryName is null</Expr>
            <Expr name="!=EMPTY">cat.categoryName is not null</Expr>
            <Expr name="!=">cat.categoryName != :categoryName</Expr>
          </DefaultExpressions>
       </Text>
       <MultiText name="itemNumbers" matchType="IEXACT" labelKey="item.multipleItemNumbers" rows="3" popupFinderName="EnterpriseItemFinder">
          <Expression>lower(im.itemNumber) in (:itemNumbers)</Expression>
       </MultiText>
       <List name="itemType" multiSelect="true" labelKey="item.type">
          <Expression>im.itemType in (:itemType)</Expression>
          <ListValue label="item.item" value="I"/>          
          <ListValue label="item.cfgGroup" value="CFG"/>
          <ListValue label="item.supplierItem" value="S"/>          
          <ListValue label="item.mfgItem" value="M"/>                                        
          <ListValue label="item.phantomItem" value="PI"/>
       </List>
       <List name="managedFlag" multiSelect="false" labelKey="mdm.managed"
          initializer="com.scplatform.pcm.searchframework.service.SearchListInitializer"
          initializerData="pcm.managedFlags">       
          <Expression>coalesce(im.managedFlag,cat.managedFlag,'N/A') = :managedFlag</Expression>                     
          <ListValue label="info.all" value=""/>       
       </List>              
       <Text name="daysOld" matchType="LE" labelKey="label.daysOld">
          <Expression>function('TRUNC', current_date - cast(im.insertDate as date)) &lt;= to_number(:daysOld)</Expression>
       </Text>
	<List name="isAssigned" multiSelect="false" labelKey="as.assigned">
          <Expression>case when :owner is null and :user is null and {VALUE} (select 1 from ItemAssignment where item = im) then 1
          when :owner is not null or :user is not null then 1 else 0 end = 1
          </Expression>           
       		<ListValue label="info.all" value="" />
		<ListValue label="info.yes" value="exists" />
		<ListValue label="info.no" value="not exists" />
       </List>
       <List name="owner" multiSelect="false" labelKey="as.responsibility"
          initializer="com.scplatform.pcm.searchframework.initializer.ResponsibilityListInitializer"
          initializerData="responsibilityType:['I'],excludeResponsibility:['BUYER']">
		 <Expression>case when (:isAssigned is null or :isAssigned = 'exists') and lower(r.responsibilityKey) = lower(:owner) then 1
		  when :isAssigned = 'not exists' and not exists (select 1 from im.assignments a where lower(a.responsibility) = lower(:owner) and (:user is null or lower(a.userId) like lower(:user))) then 1
		  else 0 end = 1
	      </Expression>
	      <ListValue label="info.all" value="" />
       </List>
       <List name="regions" multiSelect="true" labelKey="as.region"
          initializer="com.scplatform.pcm.searchframework.initializer.ResponsibilityRegionListInitializer">
          <Expression>exists (select 1 from im.assignments a left join a.regionalResponsibility rs left join rs.site st where st.siteKey in (:regions))</Expression>
       </List>
       <Text name="user" matchType="ILIKE" labelKey="as.user" finderName="ItemOwner">
          <Expression>case when (:isAssigned is null or :isAssigned = 'not null') and lower(a.userId) like lower(:user) then 1
          when :isAssigned = 'null' and :owner is null and not exists (select 1 from im.assignments a2 where lower(a2.userId) like lower(:user)) then 1
          when :isAssigned = 'null' and :owner is not null then 1
		  else 0
		  end = 1
          </Expression>
       </Text>
       <Text name="dataSource" matchType="ILIKE" labelKey="item.dataSource" finderName="dataSource">
          <Expression>lower(im.dataSource) like lower(:dataSource)</Expression>
       </Text>
    </SearchParameters>
</SearchFormDefinition>
